### ISSUE TITLE
Add PageFactory facade

### ISSUE THREAD

**Issue by Gummibeer** [Astrotomic/stancy#7]
Add a facade to access the `\Astrotomic\Stancy\Factories\PageFactory` via `\Astrotomic\Stancy\Contracts\PageFactory` service bindung.
The Facade should have all relevant methods as doc-tag for IDE support.
The naming of the facade should be `PageFactory` without any suffix.

**Comment by Djuki** [comment]
@Gummibeer I think I can take care of this.

**Comment by Gummibeer** [comment]
@Djuki feel free and go for it :)
